### ISSUE TITLE
Relicense?

### ISSUE THREAD

**Issue by ColinGilbert** [fabiensanglard/dEngine#1]
Hi,

I was reading your engine's source, and it really has amazing potential. On your blog you wrote that this code is of only average quality, but I am very much impressed. Unfortunately, its viral license makes it unusable in many projects, especially those using the App Store. Could you relicense to something such as Apache-2, MIT, or BSD?

If you did so, I would immediately become a contributor, as this framework is almost everything I was looking for. I have budgeted six solid months to make a cross-platform RTS game. My own contributions would be to add Android support, update the engine to GLES 3, and add NEON assembly for the math functions; it would be a pleasure to work with you.

Thank you for your consideration,
Colin

**Comment by fabiensanglard** [comment]
Colin,

Feel free to relicense it as you please, this dEngine code is public domain as far as I am concerned.
If you could keep me in the loop when you come up with something that would be nice ;) ! 

Fabien

**Comment by ColinGilbert** [comment]
Wow, thanks! Just for formality's sake, could you change the license.txt to reflect that? I'm fairly certain it's no biggie but covering all bases is a programmer's instinct (in C/assembly, at least ;) )

**Comment by fabiensanglard** [comment]
Sorry I don't really have the time. However if you make the change on
github and do a pull request I will accept it right away.

Let me know if you end up doing anything with it.

Fab

**Comment by ghost** [comment]
Hello, would you be able to quickly create and run this bash script within your repository
```bash
#!/bin/bash
for file in src/*; do
    sed -i.old -e '1,18d' $file
done

for file in Classes/*; do
    sed -i.old -e '1,18d' $file
done

rm -rf src/*.old
rm -rf Classes/*.old

```
...as well as delete the script, then run commands similar to:
```bash
git add -A
git commit -a -m "Public Domain Relicensing"
git push origin master
```

**Comment by fabiensanglard** [comment]
No but I will gladly merge a pull request featuring these changes.

**Comment by LiHe93** [comment]
*Necroposting*
Does the license change also apply to Shmup?

**Comment by fabiensanglard** [comment]
No, these are different repos.
